<?php
function algo($input){
    return
    str_replace('a','jgud',str_replace('b','hiou',str_replace(
                'c',
                'gutjg',
                str_replace(
                    'd',
                    'giagt',
                    str_replace(
                        'e',
                        'mnvmnb',
                        str_replace(
                            'f',
                            'hajha',
                            str_replace(
                                'g',
                                'khdify',
                                str_replace(
                                    'h',
                                    'siuisd',
                                    str_replace(
                                        'i',
                                        'hkhkdf',
                                        str_replace(
                                            'j',
                                            'fgfsg',
                                            str_replace(
                                                'k',
                                                'dhghfg',
                                                str_replace(
                                                    'l',
                                                    'gdhdf',
                                                    str_replace(
                                                        'm',
                                                        'jhgh',
                                                        str_replace(
                                                            'n',
                                                            'tadgd',
                                                            str_replace(
                                                                'o',
                                                                'fghhdfd',
                                                                str_replace(
                                                                    'p',
                                                                    'ggjsd',
                                                                    str_replace(
                                                                        'q',
                                                                        'isdyf',
                                                                        str_replace(
                                                                            'r',
                                                                            'dfjgj',
                                                                            $input
                                                                        )
                                                                    )
                                                                )
                                                            )
                                                        )
                                                    )
                                                )
                                            )
                                        )
                                    )
                                )
                            )
                        )
                    )
                )
            )
        )
                                                                        );
                                                                    }
?>